spring.application.name=KindConnect
server.port=8080

ollama.api.url=http://192.168.88.122:11434/api/generate
ollama.model=gemma4:e4b
spring.datasource.url=jdbc:postgresql://localhost:5432/kindconnect_db
spring.datasource.username=prachi
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true